##
# Makefile automatically generated by genmake 1.0, Jul-29-02
# genmake 1.0 by ma_muquit@fccc.edu
##
CC= cc
DEFS=  
PROGNAME= main
INCLUDES=  -I.
LIBS=


# replace -O with -g in order to debug

DEFINES= $(INCLUDES) $(DEFS) -DSYS_UNIX=1
CFLAGS= -O $(DEFINES)

SRCS = main.c stack.c

OBJS = main.o stack.o

.c.o:
	rm -f $@
	$(CC) $(CFLAGS) -c $*.c

all: $(PROGNAME)

$(PROGNAME) : $(OBJS)
	$(CC) $(CFLAGS) -o $(PROGNAME) $(OBJS) $(LIBS)

clean:
	rm -f $(OBJS) $(PROGNAME) core
